# Generated by Django 4.2.4 on 2023-08-05 13:20

import django.core.validators
from django.db import migrations, models

from user_auth.validators import validate_phone_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS auth;'),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('password_hash', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email')])),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[validate_phone_number])),
                ('joined_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of registration')),
                ('last_modified_dt', models.DateTimeField(auto_now=True, verbose_name='Date and time of last profile updating')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth"."user',
            },
        ),
    ]
